### PR TITLE
SVCPLAN-5555: Add support for SUSE

### PR DESCRIPTION
**Pull request by billglick**
This is being tested on `control-test-opensuse155a`.

### CODE REVIEW

**Comment by jakerundall** [comment]
This looks good to me, but I will take another look when it's moved out of draft.

**Comment by billglick** [comment]
This is still in DRAFT status because Qualys cannot yet log into the test host.

**Comment by billglick** [comment]
Qualys can log in. It has logged in Jun 10 & Jun 14. So no longer an issue.

**Review by jakerundall — APPROVED** [review]
Looks good.

**Pull request merged**
